// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTbQICkJ-DZsUUbKS_sgF1MfGg-UVQsQo',
    appId: '1:344538803202:web:3a3f4d8e40d1c8115d8b1b',
    messagingSenderId: '344538803202',
    projectId: 'food-order-app-2f635',
    authDomain: 'food-order-app-2f635.firebaseapp.com',
    storageBucket: 'food-order-app-2f635.firebasestorage.app',
    measurementId: 'G-BBY3XTHNJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUB6zM9OuUWUmq3PXfO5J3MZHKU3W4Zr8',
    appId: '1:344538803202:android:a8ff61ffb96be7695d8b1b',
    messagingSenderId: '344538803202',
    projectId: 'food-order-app-2f635',
    storageBucket: 'food-order-app-2f635.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX9XhCGyRW8AVON8jWsIgAGIBkOkIl1QI',
    appId: '1:344538803202:ios:694c461148faa0965d8b1b',
    messagingSenderId: '344538803202',
    projectId: 'food-order-app-2f635',
    storageBucket: 'food-order-app-2f635.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX9XhCGyRW8AVON8jWsIgAGIBkOkIl1QI',
    appId: '1:344538803202:ios:694c461148faa0965d8b1b',
    messagingSenderId: '344538803202',
    projectId: 'food-order-app-2f635',
    storageBucket: 'food-order-app-2f635.firebasestorage.app',
    iosBundleId: 'com.example.flutterAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTbQICkJ-DZsUUbKS_sgF1MfGg-UVQsQo',
    appId: '1:344538803202:web:6b47f181efa6fdbe5d8b1b',
    messagingSenderId: '344538803202',
    projectId: 'food-order-app-2f635',
    authDomain: 'food-order-app-2f635.firebaseapp.com',
    storageBucket: 'food-order-app-2f635.firebasestorage.app',
    measurementId: 'G-5H3JKZQXHB',
  );
}
